In [2]:
import pandas as pd

constituents = pd.read_csv(
    "../data/ind_nifty500list.csv"
)

print(constituents.head())

print("\nColumns:")
print(constituents.columns)

print("\nNumber of Stocks:")
print(len(constituents))

               Company Name                Industry     Symbol Series  \
0          360 ONE WAM Ltd.      Financial Services     360ONE     EQ
1             3M India Ltd.             Diversified    3MINDIA     EQ
2            ABB India Ltd.           Capital Goods        ABB     EQ
3                  ACC Ltd.  Construction Materials        ACC     EQ
4  ACME Solar Holdings Ltd.                   Power  ACMESOLAR     EQ

      ISIN Code
0  INE466L01038
1  INE470A01017
2  INE117A01022
3  INE012A01025
4  INE622W01025

Columns:
Index(['Company Name', 'Industry', 'Symbol', 'Series', 'ISIN Code'], dtype='str')

Number of Stocks:
500

In [3]:
symbols = (
    constituents["Symbol"]
    + ".NS"
).tolist()

print(symbols[:20])

print()

print("Total Symbols:", len(symbols))

['360ONE.NS', '3MINDIA.NS', 'ABB.NS', 'ACC.NS', 'ACMESOLAR.NS', 'AIAENG.NS', 'APLAPOLLO.NS', 'AUBANK.NS', 'AWL.NS', 'AADHARHFC.NS', 'AARTIIND.NS', 'AAVAS.NS', 'ABBOTINDIA.NS', 'ACE.NS', 'ACUTAAS.NS', 'ADANIENSOL.NS', 'ADANIENT.NS', 'ADANIGREEN.NS', 'ADANIPORTS.NS', 'ADANIPOWER.NS']

Total Symbols: 500

In [4]:
pd.Series(symbols).to_csv(
    "../data/nifty500_symbols.csv",
    index=False
)

In [11]:
import yfinance as yf

test_symbols = symbols[:10]

test_data = yf.download(
    test_symbols,
    start="2015-01-01",
    end="2026-01-01",
    auto_adjust=True,
    progress=True
)

print(test_data.shape)

[*********************100%***********************]  10 of 10 completed

(2716, 50)

In [12]:
import yfinance as yf

data = yf.download(
    symbols,
    start="2015-01-01",
    end="2026-01-01",
    auto_adjust=True,
    progress=True,
    group_by="ticker",
    threads=True
)

[*********************100%***********************]  500 of 500 completed

In [13]:
data.to_pickle(
    "../data/nifty500_ohlcv.pkl"
)

print("Saved")

Saved

In [14]:
close = pd.DataFrame()

for symbol in symbols:

    try:
        close[symbol] = data[symbol]["Close"]

    except:
        pass

print(close.shape)

close.head()

C:\Users\SaiAshwin\AppData\Local\Temp\ipykernel_19084\1048903189.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  close[symbol] = data[symbol]["Close"]

(2716, 500)

,360ONE.NS,3MINDIA.NS,ABB.NS,ACC.NS,ACMESOLAR.NS,AIAENG.NS,APLAPOLLO.NS,AUBANK.NS,AWL.NS,AADHARHFC.NS,...,WIPRO.NS,WOCKPHARMA.NS,YESBANK.NS,ZFCVINDIA.NS,ZEEL.NS,ZENTEC.NS,ZENSARTECH.NS,ZYDUSLIFE.NS,ZYDUSWELL.NS,ECLERX.NS
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-01,NaN,6042.789062,1126.536133,1236.871338,NaN,1001.922424,31.517538,NaN,NaN,NaN,...,91.154800,928.719971,147.012482,742.242615,346.171448,NaN,102.716225,292.863586,154.284592,312.330841
2015-01-02,NaN,6032.430664,1114.850952,1256.567139,NaN,1019.231934,31.723621,NaN,NaN,NaN,...,91.963379,940.678467,150.751801,766.081055,349.150146,NaN,103.885956,295.706818,152.250000,320.748352
2015-01-05,NaN,6024.022949,1115.110474,1263.396973,NaN,1023.329163,30.843063,NaN,NaN,NaN,...,92.128410,945.225464,151.075287,771.907043,348.279510,NaN,102.122894,308.742249,152.972534,320.796783
2015-01-06,NaN,5883.372070,1104.983765,1219.246460,NaN,984.705139,30.730652,NaN,NaN,NaN,...,89.974937,890.798157,146.841232,735.192200,337.189545,NaN,100.232658,301.620453,148.399551,307.776917
2015-01-07,NaN,5847.976562,1089.056885,1205.058350,NaN,969.145020,30.716604,NaN,NaN,NaN,...,89.290146,907.258240,144.119995,740.960815,334.394104,NaN,100.029236,299.567535,149.388306,308.055511

In [15]:
close = pd.DataFrame()

for symbol in symbols:

    try:
        close[symbol] = data[symbol]["Close"]

    except:
        pass

print(close.shape)

close.head()

C:\Users\SaiAshwin\AppData\Local\Temp\ipykernel_19084\1048903189.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  close[symbol] = data[symbol]["Close"]

(2716, 500)

,360ONE.NS,3MINDIA.NS,ABB.NS,ACC.NS,ACMESOLAR.NS,AIAENG.NS,APLAPOLLO.NS,AUBANK.NS,AWL.NS,AADHARHFC.NS,...,WIPRO.NS,WOCKPHARMA.NS,YESBANK.NS,ZFCVINDIA.NS,ZEEL.NS,ZENTEC.NS,ZENSARTECH.NS,ZYDUSLIFE.NS,ZYDUSWELL.NS,ECLERX.NS
Date,,,,,,,,,,,,,,,,,,,,,
2015-01-01,NaN,6042.789062,1126.536133,1236.871338,NaN,1001.922424,31.517538,NaN,NaN,NaN,...,91.154800,928.719971,147.012482,742.242615,346.171448,NaN,102.716225,292.863586,154.284592,312.330841
2015-01-02,NaN,6032.430664,1114.850952,1256.567139,NaN,1019.231934,31.723621,NaN,NaN,NaN,...,91.963379,940.678467,150.751801,766.081055,349.150146,NaN,103.885956,295.706818,152.250000,320.748352
2015-01-05,NaN,6024.022949,1115.110474,1263.396973,NaN,1023.329163,30.843063,NaN,NaN,NaN,...,92.128410,945.225464,151.075287,771.907043,348.279510,NaN,102.122894,308.742249,152.972534,320.796783
2015-01-06,NaN,5883.372070,1104.983765,1219.246460,NaN,984.705139,30.730652,NaN,NaN,NaN,...,89.974937,890.798157,146.841232,735.192200,337.189545,NaN,100.232658,301.620453,148.399551,307.776917
2015-01-07,NaN,5847.976562,1089.056885,1205.058350,NaN,969.145020,30.716604,NaN,NaN,NaN,...,89.290146,907.258240,144.119995,740.960815,334.394104,NaN,100.029236,299.567535,149.388306,308.055511

In [16]:
print(close.shape)

print(close.index.min())
print(close.index.max())

print(close.isna().sum().sort_values(ascending=False).head(20))

(2716, 500)
2015-01-01 00:00:00
2025-12-31 00:00:00
ICICIAMC.NS      2708
MEESHO.NS        2701
TENNIND.NS       2686
EMMVEE.NS        2685
PWL.NS           2685
PINELABS.NS      2683
GROWW.NS         2681
TMCV.NS          2681
LENSKART.NS      2679
PIRAMALFIN.NS    2678
CANHLIFE.NS      2665
LGEINDIA.NS      2662
TATACAP.NS       2661
JAINREC.NS       2656
URBANCO.NS       2644
JSWCEMENT.NS     2622
CPPLUS.NS        2615
ANTHEM.NS        2604
TRAVELFOOD.NS    2599
HDBFS.NS         2591
dtype: int64

In [17]:
missing_pct = close.isna().mean()

close_clean = close.loc[
    :,
    missing_pct < 0.20
]

print("Original :", close.shape)
print("Cleaned  :", close_clean.shape)

Original : (2716, 500)
Cleaned  : (2716, 332)

In [18]:
close_clean = close_clean.ffill()

close_clean.to_csv(
    "../data/nifty500_close_clean.csv"
)

close_clean.to_pickle(
    "../data/nifty500_close_clean.pkl"
)

In [19]:
import pandas as pd

open_df = pd.DataFrame()
high_df = pd.DataFrame()
low_df = pd.DataFrame()
volume_df = pd.DataFrame()

for symbol in symbols:

    try:
        open_df[symbol] = data[symbol]["Open"]
        high_df[symbol] = data[symbol]["High"]
        low_df[symbol] = data[symbol]["Low"]
        volume_df[symbol] = data[symbol]["Volume"]

    except:
        pass

print("Open  :", open_df.shape)
print("High  :", high_df.shape)
print("Low   :", low_df.shape)
print("Volume:", volume_df.shape)

C:\Users\SaiAshwin\AppData\Local\Temp\ipykernel_19084\462312307.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  open_df[symbol] = data[symbol]["Open"]
C:\Users\SaiAshwin\AppData\Local\Temp\ipykernel_19084\462312307.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  high_df[symbol] = data[symbol]["High"]
C:\Users\SaiAshwin\AppData\Local\Temp\ipykernel_19084\462312307.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  low_df[symbol] = data[symbol]["Low"]
C:\Users\SaiAshwin\AppData\Local\Temp\ipykernel_19084\462312307.py:14: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  volume_df[symbol] = data[symbol]["Volume"]

Open  : (2716, 500)
High  : (2716, 500)
Low   : (2716, 500)
Volume: (2716, 500)

In [20]:
open_df.to_pickle("../data/open.pkl")
high_df.to_pickle("../data/high.pkl")
low_df.to_pickle("../data/low.pkl")
volume_df.to_pickle("../data/volume.pkl")

print("Saved Successfully")

Saved Successfully